# Generated by Django 5.1.5 on 2025-01-31 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='opcion_entrega',
            field=models.CharField(choices=[('retiro', 'Retirar en sucursal'), ('envio', 'Envío a otra sucursal')], default='retiro', max_length=10),
        ),
    ]
