# Generated by Django 5.1.5 on 2025-01-31 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_medicamentodescrip'),
        ('sales', '0002_pedido_opcion_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='sucursal_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.sucursal'),
        ),
    ]
