# Generated by Django 5.1.5 on 2025-02-02 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicamentoSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.medicamentodescrip')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado')], max_length=20)),
                ('opcion_entrega', models.CharField(choices=[('retiro', 'Retirar en sucursal'), ('envio', 'Envío a otra sucursal')], default='retiro', max_length=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.cliente')),
                ('sucursal_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sucursal_destino', to='inventory.sucursal')),
                ('sucursal_entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.sucursal')),
                ('sucursal_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursal_origen', to='inventory.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.medicamentodescrip')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='sales.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='TransferenciaMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_transferencia', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado')], default='pendiente', max_length=20)),
                ('medicamento_sucursal_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='sales.medicamentosucursal')),
                ('medicamento_sucursal_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origen', to='sales.medicamentosucursal')),
            ],
        ),
        migrations.CreateModel(
            name='VentaMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('tipo_entrega', models.CharField(choices=[('retiro', 'Retiro en sucursal'), ('envio', 'Envío a sucursal')], max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.cliente')),
                ('medicamento_sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.medicamentosucursal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
