# Generated by Django 5.1.5 on 2025-01-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
