# Generated by Django 5.1.5 on 2025-01-27 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_medicamento_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='inventory.sucursal'),
        ),
    ]
